server:
  port: ${SERVER_PORT:8080}

spring:
  datasource:
    url: ${DATABASE_URI:jdbc:postgresql://localhost:5432/multi-tenant}
    username: ${DATABASE_USERNAME:postgres}
    password: ${DATABASE_PASSWORD:postgres123}
